/* eslint-disable */
export default [
  {
    slug: 'montana-2017',
    name: 'Montana',
    date: 'August 5-12, 2017',
    places: [
      {
        name: 'Kirk Hill',
        slug: 'kirk-hill',
        longitude: -111.0636296,
        latitude: 45.5907378,
        dates: ['2017-08-06'],
        photos: [
          {
            "SourceFile": "DSCN5338.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/800",
            "ApertureValue": 8.0,
            "FocalLength": "321.0 mm",
            "FocalLengthIn35mmFormat": "1800 mm",
            "Keywords": ["kirk hill","montana"],
            "DateCreated": "2017:08:06 09:01:28",
            "TimeCreated": "09:01:28",
            "Creator": "Shawn Taylor",
            "Title": "Kirk Hill",
            "Rights": "CC BY 3.0 US",
            "Description": "Yellow Warblers",
            "DateTimeCreated": "2017:08:06 09:01:28"
          },
          {
            "SourceFile": "IMG_7321.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/120",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["kirk hill","montana"],
            "DateCreated": "2017:08:06 07:13:41.658",
            "TimeCreated": "07:13:41",
            "Creator": "Shawn Taylor",
            "Title": "Kirk Hill",
            "Rights": "CC BY 3.0 US",
            "DateTimeCreated": "2017:08:06 07:13:41"
          },
          {
            "SourceFile": "IMG_7332.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/30",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["kirk hill","montana"],
            "DateCreated": "2017:08:06 08:11:04.012",
            "TimeCreated": "08:11:04",
            "Creator": "Shawn Taylor",
            "Title": "Kirk Hill",
            "Rights": "CC BY 3.0 US",
            "DateTimeCreated": "2017:08:06 08:11:04"
          },
        ]
      },
      {
        name: 'East Gallatin Recreation Area',
        slug: 'east-gallatin-recreation-area',
        longitude: -111.0378295,
        latitude: 45.7054113,
        dates: ['2017-08-06', '2017-08-11'],
        photos: [
          {
            "SourceFile": "IMG_7404.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/2500",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["east gallatin recreation area","montana"],
            "DateCreated": "2017:08:06 18:58:41.392",
            "TimeCreated": "18:58:41",
            "Creator": "Shawn Taylor",
            "Title": "East Gallatin Recreation Area",
            "Rights": "CC BY 3.0 US",
            "Description": "Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:06 18:58:41"
          },
          {
            "SourceFile": "DSCN7593.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/2000",
            "ApertureValue": 6.5,
            "FocalLength": "357.0 mm",
            "FocalLengthIn35mmFormat": "2000 mm",
            "Keywords": ["east gallatin recreation area","montana"],
            "DateCreated": "2017:08:11 08:16:05",
            "TimeCreated": "08:16:05",
            "Creator": "Shawn Taylor",
            "Title": "East Gallatin Recreation Area",
            "Rights": "CC BY 3.0 US",
            "Description": "Eastern Kingbird, Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:11 08:16:05"
          },
          {
            "SourceFile": "IMG_7721.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/40",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["east gallatin recreation area","montana"],
            "DateCreated": "2017:08:11 07:24:48.165",
            "TimeCreated": "07:24:48",
            "Creator": "Shawn Taylor",
            "Title": "East Gallatin Recreation Area",
            "Rights": "CC BY 3.0 US",
            "Description": "Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:11 07:24:48"
          }
        ]
      },
      {
        name: 'Swan Creek',
        slug: 'swan-creek',
        longitude: -111.1529817,
        latitude: 45.3734172,
        dates: ['2017-08-06'],
        photos: [
          {
            "SourceFile": "IMG_7362.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/700",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["montana","swan creek"],
            "DateCreated": "2017:08:06 12:39:06.977",
            "TimeCreated": "12:39:06",
            "Creator": "Shawn Taylor",
            "Title": "Swan Creek",
            "Rights": "CC BY 3.0 US",
            "DateTimeCreated": "2017:08:06 12:39:06"
          },
          {
            "SourceFile": "IMG_7378.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/750",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["montana","swan creek"],
            "DateCreated": "2017:08:06 12:49:39.314",
            "TimeCreated": "12:49:39",
            "Creator": "Shawn Taylor",
            "Title": "Swan Creek",
            "Rights": "CC BY 3.0 US",
            "DateTimeCreated": "2017:08:06 12:49:39"
          }
        ]
      },
      {
        name: 'Cherry River Fishing Access',
        slug: 'cherry-river',
        longitude: -111.0506053,
        latitude: 45.7117788,
        dates: ['2017-08-07'],
        photos: [
          {
            "SourceFile": "DSCN5942.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/2500",
            "ApertureValue": 8.0,
            "FocalLength": "196.0 mm",
            "FocalLengthIn35mmFormat": "1100 mm",
            "Keywords": ["cherry river fishing access","montana"],
            "DateCreated": "2017:08:07 08:15:05",
            "TimeCreated": "08:15:05",
            "Creator": "Shawn Taylor",
            "Title": "Cherry River Fishing Access",
            "Rights": "CC BY 3.0 US",
            "Description": "Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:07 08:15:05"
          },
          {
            "SourceFile": "IMG_7539.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/1700",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["cherry river fishing access","montana"],
            "DateCreated": "2017:08:07 18:58:30.771",
            "TimeCreated": "18:58:30",
            "Creator": "Shawn Taylor",
            "Title": "Cherry River Fishing Access",
            "Rights": "CC BY 3.0 US",
            "Description": "Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:07 18:58:30"
          },
          {
            "SourceFile": "DSCN6265.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/800",
            "ApertureValue": 8.0,
            "FocalLength": "357.0 mm",
            "FocalLengthIn35mmFormat": "2000 mm",
            "Keywords": ["cherry river fishing access","montana"],
            "DateCreated": "2017:08:07 19:11:51",
            "TimeCreated": "19:11:51",
            "Creator": "Shawn Taylor",
            "Title": "Cherry River Fishing Access",
            "Rights": "CC BY 3.0 US",
            "Description": "Pied-billed Grebe, Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:07 19:11:51"
          }
        ]
      },
      {
        name: 'Mammoth Hot Springs, Yellowstone National Park',
        slug: 'yellowstone',
        longitude: -110.705106,
        latitude: 44.9706559,
        dates: ['2017-08-07'],
        photos: [
          {
            "SourceFile": "IMG_7474.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/4300",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["montana","yellowstone"],
            "DateCreated": "2017:08:07 13:05:39.066",
            "TimeCreated": "13:05:39",
            "Creator": "Shawn Taylor",
            "Title": "Yellowstone National Park",
            "Rights": "CC BY 3.0 US",
            "Description": "Mammoth Hot Springs",
            "DateTimeCreated": "2017:08:07 13:05:39"
          },
          {
            "SourceFile": "IMG_7491.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/3300",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["montana","yellowstone"],
            "DateCreated": "2017:08:07 13:14:05.111",
            "TimeCreated": "13:14:05",
            "Creator": "Shawn Taylor",
            "Title": "Yellowstone National Park",
            "Rights": "CC BY 3.0 US",
            "Description": "Mammoth Hot Springs",
            "DateTimeCreated": "2017:08:07 13:14:05"
          },
          {
            "SourceFile": "DSCN6213.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/3200",
            "ApertureValue": 8.0,
            "FocalLength": "89.2 mm",
            "FocalLengthIn35mmFormat": "500 mm",
            "Keywords": ["montana","yellowstone"],
            "DateCreated": "2017:08:07 13:19:10",
            "TimeCreated": "13:19:10",
            "Creator": "Shawn Taylor",
            "Title": "Yellowstone National Park",
            "Rights": "CC BY 3.0 US",
            "Description": "Swallow, Mammoth Hot Springs",
            "DateTimeCreated": "2017:08:07 13:19:10"
          }
        ]
      },
      {
        name: 'Burke Park Trail',
        slug: 'burke-park',
        longitude: -111.0289152,
        latitude: 45.6719752,
        dates: ['2017-08-08', '2017-08-12'],
        photos: [
          {
            "SourceFile": "IMG_7552.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/300",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["burke park","lindley park","main street to the mountains","montana"],
            "DateCreated": "2017:08:08 07:31:21.531",
            "TimeCreated": "07:31:21",
            "Creator": "Shawn Taylor",
            "Title": "Burke Park Trail",
            "Rights": "CC BY 3.0 US",
            "Description": "Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:08 07:31:21"
          },
          {
            "SourceFile": "DSCN6381.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/1250",
            "ApertureValue": 8.0,
            "FocalLength": "357.0 mm",
            "FocalLengthIn35mmFormat": "2000 mm",
            "Keywords": ["burke park","lindley park","main street to the mountains","montana"],
            "DateCreated": "2017:08:08 07:59:44",
            "TimeCreated": "07:59:44",
            "Creator": "Shawn Taylor",
            "Title": "Burke Park Trail",
            "Rights": "CC BY 3.0 US",
            "Description": "Black-Capped Chickadees, Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:08 07:59:44"
          },
          {
            "SourceFile": "IMG_7828.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/950",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["burke park","lindley park","montana"],
            "DateCreated": "2017:08:12 07:48:38.753",
            "TimeCreated": "07:48:38",
            "Creator": "Shawn Taylor",
            "Title": "Burke Park Trail",
            "Rights": "CC BY 3.0 US",
            "Description": "Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:12 07:48:38"
          }
        ]
      },
      {
        name: 'Missouri Headwaters State Park',
        slug: 'missouri-headwaters',
        longitude: -111.5017071,
        latitude: 45.9283136,
        dates: ['2017-08-08'],
        photos: [
          {
            "SourceFile": "IMG_7570.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/2200",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["missouri headwaters state park","montana"],
            "DateCreated": "2017:08:08 10:15:22.900",
            "TimeCreated": "10:15:22",
            "Creator": "Shawn Taylor",
            "Title": "Missouri Headwaters State Park",
            "Rights": "CC BY 3.0 US",
            "Description": "Madison River",
            "DateTimeCreated": "2017:08:08 10:15:22"
          },
          {
            "SourceFile": "DSCN6463.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/800",
            "ApertureValue": 8.0,
            "FocalLength": "268.0 mm",
            "FocalLengthIn35mmFormat": "1500 mm",
            "Keywords": ["missouri headwaters state park","montana"],
            "DateCreated": "2017:08:08 10:53:23",
            "TimeCreated": "10:53:23",
            "Creator": "Shawn Taylor",
            "Title": "Missouri Headwaters State Park",
            "Rights": "CC BY 3.0 US",
            "Description": "Gopher Snake, Fort Rock",
            "DateTimeCreated": "2017:08:08 10:53:23"
          },
          {
            "SourceFile": "IMG_7588.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/2500",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["missouri headwaters state park","montana"],
            "DateCreated": "2017:08:08 11:05:01.631",
            "TimeCreated": "11:05:01",
            "Creator": "Shawn Taylor",
            "Title": "Missouri Headwaters State Park",
            "Rights": "CC BY 3.0 US",
            "Description": "Fort Rock",
            "DateTimeCreated": "2017:08:08 11:05:01"
          }
        ]
      },
      {
        name: 'Hyalite Reservoir',
        slug: 'hyalite-reservoir',
        longitude: -110.967416,
        latitude: 45.4812828,
        dates: ['2017-08-09'],
        photos: [
          {
            "SourceFile": "FullSizeRender 22.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/3000",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["hyalite reservoir","montana"],
            "DateCreated": "2017:08:09 10:42:14",
            "TimeCreated": "10:42:14",
            "Creator": "Shawn Taylor",
            "Title": "Hyalite Reservoir",
            "Rights": "CC BY 3.0 US",
            "DateTimeCreated": "2017:08:09 10:42:14"
          },
          {
            "SourceFile": "DSCN6762.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/1600",
            "ApertureValue": 8.0,
            "FocalLength": "285.0 mm",
            "FocalLengthIn35mmFormat": "1600 mm",
            "Keywords": ["hyalite reservoir","montana"],
            "DateCreated": "2017:08:09 12:05:58",
            "TimeCreated": "12:05:58",
            "Creator": "Shawn Taylor",
            "Title": "Hyalite Reservoir",
            "Rights": "CC BY 3.0 US",
            "Description": "Spotted Sandpiper",
            "DateTimeCreated": "2017:08:09 12:05:58"
          },
          {
            "SourceFile": "DSCN6874.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/1250",
            "ApertureValue": 8.0,
            "FocalLength": "357.0 mm",
            "FocalLengthIn35mmFormat": "2000 mm",
            "Keywords": ["hyalite reservoir","montana"],
            "DateCreated": "2017:08:09 12:35:46",
            "TimeCreated": "12:35:46",
            "Creator": "Shawn Taylor",
            "Title": "Hyalite Reservoir",
            "Rights": "CC BY 3.0 US",
            "Description": "American Avocet",
            "DateTimeCreated": "2017:08:09 12:35:46"
          }
        ]
      },
      {
        name: 'Palisade Falls',
        slug: 'palisade-falls',
        longitude: -110.9318704,
        latitude: 45.4692005,
        dates: ['2017-08-09'],
        photos: [
          {
            "SourceFile": "DSCN6746.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/2000",
            "ApertureValue": 8.0,
            "FocalLength": "107.0 mm",
            "FocalLengthIn35mmFormat": "600 mm",
            "Keywords": ["montana","palisade falls"],
            "DateCreated": "2017:08:09 11:16:22",
            "TimeCreated": "11:16:22",
            "Creator": "Shawn Taylor",
            "Title": "Palisade Falls",
            "Rights": "CC BY 3.0 US",
            "Description": "Pika with leaves",
            "DateTimeCreated": "2017:08:09 11:16:22"
          },
          {
            "SourceFile": "DSCN6748.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/1250",
            "ApertureValue": 8.0,
            "FocalLength": "357.0 mm",
            "FocalLengthIn35mmFormat": "2000 mm",
            "Keywords": ["montana","palisade falls"],
            "DateCreated": "2017:08:09 11:16:56",
            "TimeCreated": "11:16:56",
            "Creator": "Shawn Taylor",
            "Title": "Palisade Falls",
            "Rights": "CC BY 3.0 US",
            "Description": "Pika",
            "DateTimeCreated": "2017:08:09 11:16:56"
          },
          {
            "SourceFile": "IMG_7631.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/380",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["montana","palisade falls"],
            "DateCreated": "2017:08:09 11:24:58.740",
            "TimeCreated": "11:24:58",
            "Creator": "Shawn Taylor",
            "Rights": "CC BY 3.0 US",
            "DateTimeCreated": "2017:08:09 11:24:58"
          },
        ]
      },
      {
        name: 'Ennis Lake',
        slug: 'ennis-lake',
        longitude: -111.6882102,
        latitude: 45.4328954,
        dates: ['2017-08-10'],
        photos: [
          {
            "SourceFile": "DSCN7025.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/800",
            "ApertureValue": 8.0,
            "FocalLength": "170.0 mm",
            "FocalLengthIn35mmFormat": "950 mm",
            "Keywords": ["ennis lake","montana"],
            "DateCreated": "2017:08:10 09:57:17",
            "TimeCreated": "09:57:17",
            "Creator": "Shawn Taylor",
            "Title": "Ennis Lake",
            "Rights": "CC BY 3.0 US",
            "Description": "American White Pelican",
            "DateTimeCreated": "2017:08:10 09:57:17"
          },
          {
            "SourceFile": "DSCN7168.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/500",
            "ApertureValue": 8.0,
            "FocalLength": "39.3 mm",
            "FocalLengthIn35mmFormat": "220 mm",
            "Keywords": ["ennis lake","montana"],
            "DateCreated": "2017:08:10 11:02:41",
            "TimeCreated": "11:02:41",
            "Creator": "Shawn Taylor",
            "Title": "Ennis Lake",
            "Rights": "CC BY 3.0 US",
            "Description": "California Gull",
            "DateTimeCreated": "2017:08:10 11:02:41"
          },
          {
            "SourceFile": "DSCN7260.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/3200",
            "ApertureValue": 8.0,
            "FocalLength": "107.0 mm",
            "FocalLengthIn35mmFormat": "600 mm",
            "Keywords": ["ennis lake","montana"],
            "DateCreated": "2017:08:10 11:24:26",
            "TimeCreated": "11:24:26",
            "Creator": "Shawn Taylor",
            "Title": "Ennis Lake",
            "Rights": "CC BY 3.0 US",
            "Description": "Osprey",
            "DateTimeCreated": "2017:08:10 11:24:26"
          }
        ]
      },
      {
        name: 'Springhill/Dry Creek Birding Loop',
        slug: 'birding-loop',
        longitude: -111.1212171,
        latitude: 45.8180368,
        dates: ['2017-08-11'],
        photos: [
          {
            "SourceFile": "DSCN7659.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/2000",
            "ApertureValue": 6.5,
            "FocalLength": "357.0 mm",
            "FocalLengthIn35mmFormat": "2000 mm",
            "Keywords": ["montana","springhill/dry creek loop"],
            "DateCreated": "2017:08:11 10:44:42",
            "TimeCreated": "10:44:42",
            "Creator": "Shawn Taylor",
            "Title": "Springhill/Dry Creek Loop",
            "Rights": "CC BY 3.0 US",
            "Description": "American Kestrel",
            "DateTimeCreated": "2017:08:11 10:44:42"
          },
          {
            "SourceFile": "DSCN7775.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/2000",
            "ApertureValue": 6.3,
            "FocalLength": "178.0 mm",
            "FocalLengthIn35mmFormat": "1000 mm",
            "Keywords": ["montana","springhill/dry creek loop"],
            "DateCreated": "2017:08:11 11:01:33",
            "TimeCreated": "11:01:33",
            "Creator": "Shawn Taylor",
            "Title": "Springhill/Dry Creek Loop",
            "Rights": "CC BY 3.0 US",
            "Description": "Mountain Bluebird",
            "DateTimeCreated": "2017:08:11 11:01:33"
          },
          {
            "SourceFile": "DSCN7778.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/1600",
            "ApertureValue": 6.3,
            "FocalLength": "196.0 mm",
            "FocalLengthIn35mmFormat": "1100 mm",
            "Keywords": ["montana","springhill/dry creek loop"],
            "DateCreated": "2017:08:11 11:09:39",
            "TimeCreated": "11:09:39",
            "Creator": "Shawn Taylor",
            "Title": "Springhill/Dry Creek Loop",
            "Rights": "CC BY 3.0 US",
            "DateTimeCreated": "2017:08:11 11:09:39"
          }
        ]
      },
      {
        name: 'Triple Tree Trail',
        slug: 'triple-tree',
        longitude: -111.0042353,
        latitude: 45.611565,
        dates: ['2017-08-11'],
        photos: [
          {
            "SourceFile": "DSCN7835.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/1600",
            "ApertureValue": 6.3,
            "FocalLength": "53.5 mm",
            "FocalLengthIn35mmFormat": "300 mm",
            "Keywords": ["montana","triple tree trail"],
            "DateCreated": "2017:08:11 14:39:02",
            "TimeCreated": "14:39:02",
            "Creator": "Shawn Taylor",
            "Title": "Triple Tree Trail",
            "Rights": "CC BY 3.0 US",
            "Description": "Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:11 14:39:02"
          },
          {
            "SourceFile": "IMG_7732.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/500",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["montana","triple tree trail"],
            "DateCreated": "2017:08:11 14:54:26.934",
            "TimeCreated": "14:54:26",
            "Creator": "Shawn Taylor",
            "Title": "Triple Tree Trail",
            "Rights": "CC BY 3.0 US",
            "Description": "Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:11 14:54:26"
          },
          {
            "SourceFile": "DSCN7952.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/1000",
            "ApertureValue": 6.5,
            "FocalLength": "357.0 mm",
            "FocalLengthIn35mmFormat": "2000 mm",
            "Keywords": ["montana","triple tree trail"],
            "DateCreated": "2017:08:11 16:15:48",
            "TimeCreated": "16:15:48",
            "Creator": "Shawn Taylor",
            "Title": "Triple Tree Trail",
            "Rights": "CC BY 3.0 US",
            "Description": "Western Tanager, Main Street to the Mountains Trail",
            "DateTimeCreated": "2017:08:11 16:15:48"
          }
        ]
      },
      {
        name: 'Blacks Ford/Greycliff',
        slug: 'blacks-ford',
        longitude: -111.5152849,
        latitude: 45.7141624,
        dates: ['2017-08-12'],
        photos: [
          {
            "SourceFile": "DSCN8010.jpg",
            "Make": "NIKON",
            "Model": "COOLPIX P900",
            "ShutterSpeedValue": "1/1250",
            "ApertureValue": 6.3,
            "FocalLength": "152.0 mm",
            "FocalLengthIn35mmFormat": "850 mm",
            "Keywords": "black's ford",
            "DateCreated": "2017:08:12 11:05:29",
            "TimeCreated": "11:05:29",
            "Creator": "Shawn Taylor",
            "Title": "Blacks Ford",
            "Rights": "CC BY 3.0 US",
            "Description": "Sandhill Cranes",
            "DateTimeCreated": "2017:08:12 11:05:29"
          },
          {
            "SourceFile": "IMG_7846.jpg",
            "Make": "Apple",
            "Model": "iPhone SE",
            "ShutterSpeedValue": "1/1250",
            "ApertureValue": 2.2,
            "FocalLength": "4.2 mm",
            "FocalLengthIn35mmFormat": "29 mm",
            "Keywords": ["black's ford","montana"],
            "DateCreated": "2017:08:12 09:58:35.545",
            "TimeCreated": "09:58:35",
            "Creator": "Shawn Taylor",
            "Title": "Blacks Ford",
            "Rights": "CC BY 3.0 US",
            "DateTimeCreated": "2017:08:12 09:58:35"
          }
        ]
      }
    ]
  }
]
